// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ1mtdbzQInACljsZR-0tgwviJOLDI2kU',
    appId: '1:770114382167:web:bc4116cf5722bc31c3b612',
    messagingSenderId: '770114382167',
    projectId: 'flutterapp-5561d',
    authDomain: 'flutterapp-5561d.firebaseapp.com',
    storageBucket: 'flutterapp-5561d.appspot.com',
    measurementId: 'G-04J85718WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8FfSrjKrV6LscnkgCHpYk6FoHAFiSlw',
    appId: '1:770114382167:android:b68b2e605bc87e0dc3b612',
    messagingSenderId: '770114382167',
    projectId: 'flutterapp-5561d',
    storageBucket: 'flutterapp-5561d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA47scx_QAVh71S24-LU_7mL9bD4w77j_Q',
    appId: '1:770114382167:ios:e34ea82f2cd77715c3b612',
    messagingSenderId: '770114382167',
    projectId: 'flutterapp-5561d',
    storageBucket: 'flutterapp-5561d.appspot.com',
    iosBundleId: 'com.example.myflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA47scx_QAVh71S24-LU_7mL9bD4w77j_Q',
    appId: '1:770114382167:ios:e77ffcb86053f2f6c3b612',
    messagingSenderId: '770114382167',
    projectId: 'flutterapp-5561d',
    storageBucket: 'flutterapp-5561d.appspot.com',
    iosBundleId: 'com.example.myflutterapp.RunnerTests',
  );
}
