// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJqrW4T5UFUJJEY9vLrK5GEcSMR_gm0L4',
    appId: '1:219045007651:web:a7cee95b8e541805977c96',
    messagingSenderId: '219045007651',
    projectId: 'flutterfirebase-b7be4',
    authDomain: 'flutterfirebase-b7be4.firebaseapp.com',
    storageBucket: 'flutterfirebase-b7be4.appspot.com',
    measurementId: 'G-CF7NVPW7MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcDW2VKIgFIuiQKbPESuXpC99eaHrBPp4',
    appId: '1:219045007651:android:264f5a1dd7b886cc977c96',
    messagingSenderId: '219045007651',
    projectId: 'flutterfirebase-b7be4',
    storageBucket: 'flutterfirebase-b7be4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbKG_FltClI9jRDluz6cw9xmR-siP8bS0',
    appId: '1:219045007651:ios:d17c689f395ad101977c96',
    messagingSenderId: '219045007651',
    projectId: 'flutterfirebase-b7be4',
    storageBucket: 'flutterfirebase-b7be4.appspot.com',
    iosBundleId: 'com.example.myflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbKG_FltClI9jRDluz6cw9xmR-siP8bS0',
    appId: '1:219045007651:ios:b20d0a618349c976977c96',
    messagingSenderId: '219045007651',
    projectId: 'flutterfirebase-b7be4',
    storageBucket: 'flutterfirebase-b7be4.appspot.com',
    iosBundleId: 'com.example.myflutterapp.RunnerTests',
  );
}
